import { DashboardComponent } from './dashboard/dashboard.component';
import { ContactsComponent } from './contacts/contacts.component';
import { TeamboxComponent } from './teambox/teambox.component';
import { ImportComponent } from './import/import.component';
import { CampaignsComponent } from './campaigns/campaigns.component';
import { FunnelComponent } from './funnel/funnel.component';
import { SmartRepliesComponent } from './smartReplies/smartReplies.component';
import { FlowBuilderComponent } from './flowBuilder/flowBuilder.component';
import { ReportsComponent } from './reports/reports.component';
import { ConversationalReportsComponent } from './conversational-reports/conversational-reports.component';
import { CampaignReportsComponent } from './campaign-reports/campaign-reports.component';
import { AutomationReportsComponent } from './automation-reports/automation-reports.component';
import { SettingComponent } from './setting/setting.component';
import { RolesSettingsComponent } from './roles-settings/roles-settings.component';
import { OrganisationalSettingsComponent } from './organisational-settings/organisational-settings.component';
import { WorkingHoursComponent } from './working-hours/working-hours.component';
import { AcoountSettingsComponent } from './acoount-settings/acoount-settings.component';
import { NotificationsComponent } from './notifications/notifications.component';
import { MyprofileComponent } from './myprofile/myprofile.component';
import { ManageplanComponent } from './manageplan/manageplan.component';
import { WalletusageComponent } from './walletusage/walletusage.component';
import { BillinghistoryComponent } from './billinghistory/billinghistory.component';
import { SupportComponent } from './support/support.component';
import { UserguideComponent } from './userguide/userguide.component';
import { DefaultMessageSettingsComponent } from './default-message-settings/default-message-settings.component';
import { GeneralSettingsComponent } from './general-settings/general-settings.component';
import { ManageStorageComponent } from './manage-storage/manage-storage.component';
import { RoutingRulesComponent } from './routing-rules/routing-rules.component';
import { TeamSettingsComponent } from './team-settings/team-settings.component';
import { UserSettingsComponent } from './user-settings/user-settings.component';
import { CampaignSettingsComponent } from './campaign-settings/campaign-settings.component';
import { ContactSettingsComponent } from './contact-settings/contact-settings.component';
import { CustomFieldsComponent } from './custom-fields/custom-fields.component';
import { TemplateSettingsComponent } from './template-settings/template-settings.component';
import { TemplateMessageComponent } from './template-message/template-message.component';
import { QuickResponseComponent } from './quick-response/quick-response.component';

export const containers = [DashboardComponent, ContactsComponent, TeamboxComponent, FlowBuilderComponent, SmartRepliesComponent, ImportComponent, CampaignsComponent,FunnelComponent, ReportsComponent,ConversationalReportsComponent, CampaignReportsComponent, AutomationReportsComponent, SettingComponent,AcoountSettingsComponent,NotificationsComponent,SupportComponent,UserguideComponent,MyprofileComponent,ManageplanComponent,WalletusageComponent,BillinghistoryComponent,OrganisationalSettingsComponent,WorkingHoursComponent,RolesSettingsComponent,DefaultMessageSettingsComponent,GeneralSettingsComponent,ManageStorageComponent,RoutingRulesComponent,TeamSettingsComponent,UserSettingsComponent,CampaignSettingsComponent,ContactSettingsComponent,CustomFieldsComponent,TemplateSettingsComponent,TemplateMessageComponent,QuickResponseComponent];

export * from './dashboard/dashboard.component';
export * from './contacts/contacts.component';
export * from './teambox/teambox.component';
export * from './import/import.component';
export * from './campaigns/campaigns.component';
export * from './funnel/funnel.component';
export * from './flowBuilder/flowBuilder.component';
export * from './smartReplies/smartReplies.component';
export * from './reports/reports.component';
export * from './conversational-reports/conversational-reports.component';
export * from './campaign-reports/campaign-reports.component';
export * from './automation-reports/automation-reports.component';
export * from './setting/setting.component';
export * from './organisational-settings/organisational-settings.component';
export * from './working-hours/working-hours.component';
export * from './notifications/notifications.component';
export * from './myprofile/myprofile.component';
export * from './manageplan/manageplan.component';
export * from './walletusage/walletusage.component';
export * from './billinghistory/billinghistory.component';
export * from './support/support.component';
export * from './userguide/userguide.component';
export * from './roles-settings/roles-settings.component';
export * from './default-message-settings/default-message-settings.component';
export * from './general-settings/general-settings.component';
export * from './manage-storage/manage-storage.component';
export * from './routing-rules/routing-rules.component';
export * from './team-settings/team-settings.component';
export * from './user-settings/user-settings.component';
export * from './campaign-settings/campaign-settings.component';
export * from './contact-settings/contact-settings.component';
export * from './custom-fields/custom-fields.component';
export * from './template-settings/template-settings.component';
export * from './template-message/template-message.component';
export * from './quick-response/quick-response.component';
